

preprocess_data <- function(data_list=PanethAnalysis::raw_data){

  message("Reading data...")

  # Give cells unique names so they can be merged
  for (table in 1:length(data_list)){
    colnames(data_list[[table]]) <- paste0(colnames(data_list[[table]]),"_",gsub(".*_","",names(data_list)[table]))
  }

  # Create a metadata list with fields not generated by Seurat
  message("Preprocessing...")
  mito_pattern <- "^MT-"
  meta_list <- lapply(seq_along(data_list),function(index) {
    percent_mito <- 100 * Matrix::colSums(data_list[[index]][grep(mito_pattern, rownames(data_list[[index]])), ]) / Matrix::colSums(data_list[[index]])

    log2_transcript_counts <- log2(Matrix::colSums(data_list[[index]][-grep(mito_pattern, rownames(data_list[[index]])),]) + 1) # Excluding mito genes (will be removed)
    log2_feature_counts <- log2(Matrix::colSums(data_list[[index]][-grep(mito_pattern, rownames(data_list[[index]])),] > 0) + 1) # Excluding mito genes (will be removed)

    data.frame("percent_mito" = percent_mito,
               "log2_counts" = log2_transcript_counts,
               "log2_features" = log2_feature_counts,
               "condition" = rep(names(data_list)[[index]],ncol(data_list[[index]])))
  })

  # Match data_list and meta_list names
  names(meta_list) <- names(data_list)

  # Merge data and metadata
  message("Merging files...")
  data_merged <- lapply(data_list, as.data.frame) %>% dplyr::bind_cols()
  meta_merged <- meta_list %>% dplyr::bind_rows()

  # Remove mtiochondrial genes and stressed cells
  data_merged <- data_merged[-grep(mito_pattern, rownames(data_merged)),]
  data_merged <- data_merged %>% dplyr::select(-PanethAnalysis::stressed_cells)

  # Create Seurat object and filter
  message("Creating Seurat object and filtering...")
  srat <- suppressWarnings(Seurat::CreateSeuratObject(data_merged, min.cells = 3, project = "IL22",
                                              meta.data = meta_merged))

  srat <- subset(srat, subset = nCount_RNA >= 3000 & nCount_RNA < 60000 & percent_mito < 25)

  return(srat)
}



integrate_data <- function(data=NULL){

  # Split object by culture condition and normalize using SCTransform
  srat.list <- Seurat::SplitObject(data, split.by = "condition")
  srat.list <- lapply(X = srat.list, FUN = Seurat::SCTransform)

  # Select integration features and run integration pipeline
  features <- Seurat::SelectIntegrationFeatures(object.list = srat.list, nfeatures = 3000)
  srat.list <- Seurat::PrepSCTIntegration(object.list = srat.list, anchor.features = features)

  srat.anchors <- Seurat::FindIntegrationAnchors(object.list = srat.list, normalization.method = "SCT",
                                         anchor.features = features)
  srat.combined.sct <- Seurat::IntegrateData(anchorset = srat.anchors, normalization.method = "SCT")

  return(srat.combined.sct)
}


process_data <- function(data=NULL){
  # Run dimensional reduction (PCA then UMAP)
  umap_pcs <- 1:25
  message("Running PCA...")
  srat <- Seurat::RunPCA(data, verbose=F)
  message("Running UMAP...")
  srat <- suppressWarnings(RunUMAP(srat, reduction = "pca", dims = umap_pcs, verbose=F))

  # Run graph-based clustering
  message("Running graph-based clustering...")
  srat <- Seurat::FindNeighbors(srat, reduction = "pca", dims = umap_pcs, verbose=F)
  srat <- Seurat::FindClusters(srat, resolution = 0.8, graph.name = "integrated_snn",algorithm = 4)

  Seurat::DefaultAssay(srat) <- "SCT"

  # Run Cell cycle scoring
  message("Running cell cycle inference...")
  srat <- Seurat::CellCycleScoring(object = srat, s.features = PanethAnalysis::cc_genes[1:43],
                           g2m.features = PanethAnalysis::cc_genes[44:97], set.ident = FALSE)

  message("Annotating clusters...")

  # Score Paneth cell module
  paneth.genes <- c("DEFA6","PLA2G2A","PRSS2","REG3A","ITLN2","defa5-ires2-dsred")
  paneth.score <- testModuleScore(Seurat::GetAssayData(srat),
                                  genes.list = list(paneth.genes), uniqueOnly = F, ctrl.size = 100)

  srat <- Seurat::AddMetaData(srat, paneth.score, col.name= "Paneth_score")

  # Rename clusters
  Seurat::Idents(srat) <- "integrated_snn_res.0.8"
  new.ids <- plyr::mapvalues(Idents(srat), from = c(1,2,3,4,5,6,7,8,9,10,11,12),
                       to = c("Early EC","EC","EC","TA2","ISC","Goblet","TA1","TA1","Secretory progenitor","TA1","TA1","EEC"))

  Seurat::Idents(srat) <- new.ids

  # Select tuft cells (AVIL expressing)
  srat <- Seurat::FindSubCluster(srat, cluster = "Secretory progenitor", resolution = 1, algorithm = 4, graph.name = "integrated_snn")
  Seurat::Idents(srat, cells=Seurat::WhichCells(srat, expression = sub.cluster =="Secretory progenitor_6")) <- "Tuft"

  # Select Paneth cells
  Seurat::Idents(srat, cells = Seurat::WhichCells(srat, expression = Paneth_score > 1.5)) <- "Paneth"

  srat <- Seurat::AddMetaData(srat, Idents(srat), "Final.IDS")

  return(srat)
}





